version: '3'
services:
  db:
    container_name: db
    restart: always
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    volumes:
      - ./db/init-user-db.sql:/docker-entrypoint-initdb.d/init.sql
      - db_vol:/var/lib/postgresql/data/
    ports:
      - "8001:5432"
    networks:
      - network1      
  api:
    container_name: api
    build: './api'
    ports:
      - "5000:5000"    
    networks:
      - network1
      - network2
  front:
    container_name: front
    build: './front'
    stdin_open: true
    tty: true   
    networks:
      - network2   
volumes:
  db_vol:
    external: true
networks:
  network1:
    driver: bridge      
  network2:
    driver: bridge      
    
